- hosts: webservers
  vars: 
    users:
      - jaime
      - sansa
      - robert
  tasks:
  - name: remove git
    ansible.builtin.apt: 
      name: git
      state: absent
    become: yes
    when: ansible_os_family == "Debian"

  - name: Remove gitconfig
    ansible.builtin.file:
      path: "/home/{{ item }}/.gitconfig"
      state: absent
    loop: "{{ users }}"
    when: ansible_os_family == "Debian"