- hosts: webservers
  vars: 
    users:
      - jaime
      - sansa
      - robert
  tasks:
  - name: install git
    ansible.builtin.apt: 
      name: git
      state: present
      update_cache: yes
    become: yes
    tags: install
    when: ansible_os_family == "Debian"
  
  - name: create users
    ansible.builtin.user:
      name: "{{ item }}"
      state: present
    loop: "{{ users }}"
    when: ansible_os_family == "Debian"
  
  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
      user: "{{ item }}"
      state: present
      key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
    loop: "{{ users }}"
    when: ansible_os_family == "Debian"
  
  - name: create gitconfig
    ansible.builtin.template:
      src: files/.gitconfig
      dest: "/home/{{ item }}/.gitconfig"
    loop: "{{ users }}"
    when: ansible_os_family == "Debian"